title: Angela Li
email: angela.li1@ucalgary.ca
description: Data Science Portfolio
url: "https://firekeepur.github.io"
baseurl: "/angela-li.github.io"
author:
  name: Angela Li
  avatar: "/assets/images/profile.jpg"
  email: angela.li1@ucalgary.ca
  github: firekeepur
  linkedin: angela-li-520520
  linktree: firekeepur
theme: beautiful-jekyll
plugins:
  - jekyll-feed
